import { expect, test, Page } from "@playwright/test";
import {
  enableAdvancedMode,
  getFixturePath,
  navigateToTab,
  setupTestEnvironment,
  TabId,
  lyricsText,
} from "./utils";

const ASS_INPUT = '[name="ass-file-upload"] input[type="file"]';
const IMPORTED_LYRICS = ["Pale_moon_ri/sing", "o/ver_the_hill", "", "Home_a/gain"].join("\n");

async function lyricsEditorValue(page: Page): Promise<string> {
  await navigateToTab(page, TabId.LyricInput);
  const value = await lyricsText(page);
  await navigateToTab(page, TabId.SongInfo);
  return value;
}

test.describe("ASS subtitle files", () => {
  test.beforeEach(async ({ page }) => {
    await setupTestEnvironment(page);
    await enableAdvancedMode(page);
    await navigateToTab(page, TabId.SongInfo);
  });

  test("loading an ASS file fills in the lyrics, timings and song title", async ({ page }) => {
    await page.locator(ASS_INPUT).setInputFiles(getFixturePath("song.ass"));

    await expect(page.locator(".toast")).toContainText("with a few changes");
    const warnings = page.locator(".ass-files .import-warnings");
    await expect(warnings).toContainText(
      "Lines generated by a karaoke effect were dropped, and the lines they were made from imported",
    );
    await expect(warnings).toContainText("Screen breaks were placed at pauses in the singing");
    await expect(page.locator('[name="ass-file-upload"] .file-name')).toHaveText("song.ass");
    await expect(page.locator('[name="title"]')).toHaveValue("Pale Moon");
    expect(await lyricsEditorValue(page)).toBe(IMPORTED_LYRICS);

    await page.locator('[name="ass-file-upload"] button.is-danger').click();
    await expect(warnings).toBeHidden();
  });

  test("asks before an ASS file replaces loaded lyrics", async ({ page }) => {
    await page
      .locator('[name="lyrics-file-upload"] input[type="file"]')
      .setInputFiles(getFixturePath("lyrics.txt"));
    const original = await lyricsEditorValue(page);

    await page.locator(ASS_INPUT).setInputFiles(getFixturePath("song.ass"));
    await expect(page.locator(".modal-card-title")).toHaveText("Replace your lyrics and timings?");
    await page.click('.modal-card-foot button:has-text("Keep what I have")');
    expect(await lyricsEditorValue(page)).toBe(original);

    await page.locator(ASS_INPUT).setInputFiles(getFixturePath("song.ass"));
    await page.click('.modal-card-foot button:has-text("Replace")');
    await expect(page.locator('[name="ass-file-upload"] .file-name')).toHaveText("song.ass");
    expect(await lyricsEditorValue(page)).toBe(IMPORTED_LYRICS);
  });
});
