import { describe, expect, it } from "vitest";
import { parseAss, parseColor, parseKaraoke, parseTimecode } from "./ass";

describe("parseAss", () => {
  it("reads the script info, styles and events by their Format lines", () => {
    const document = parseAss(
      [
        "﻿[Script Info]",
        "; Script generated by Aegisub 3.3.3",
        "Title: Pale Moon",
        "PlayResY: 720",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Outline",
        "Style: Lead,Georgia,48,&H000000FF,&H00FF0000,&H0000FF00,&H80102030,-1,0,2.5",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
        "Comment: 0,0:00:01.50,0:00:03.00,Lead,Anna,0,0,12,karaoke,{\\k50}One, {\\k100}two",
        "Dialogue: 1,1:02:03.04,1:02:04.00,*Lead,,0,0,0,,Three",
      ].join("\r\n"),
    );

    expect(document.info).toEqual({ Title: "Pale Moon", PlayResY: "720" });
    expect(document.comments).toEqual(["Script generated by Aegisub 3.3.3"]);
    expect(document.styles).toEqual([
      {
        name: "Lead",
        fontName: "Georgia",
        fontSize: 48,
        primary: "#FF0000",
        secondary: "#0000FF",
        outline: "#00FF00",
        back: "#302010",
        bold: true,
        italic: false,
        outlineWidth: 2.5,
      },
    ]);
    expect(document.events).toEqual([
      {
        comment: true,
        start: 150,
        end: 300,
        style: "Lead",
        name: "Anna",
        marginV: 12,
        effect: "karaoke",
        text: "{\\k50}One, {\\k100}two",
      },
      {
        comment: false,
        start: 372304,
        end: 372400,
        style: "Lead",
        name: "",
        marginV: 0,
        effect: "",
        text: "Three",
      },
    ]);
  });

  it("falls back to the standard event fields without a Format line", () => {
    const document = parseAss("[Events]\nDialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,Hi");
    expect(document.events[0]).toMatchObject({
      start: 100,
      end: 200,
      style: "Default",
      text: "Hi",
    });
  });

  it("throws on a file without events", () => {
    expect(() => parseAss("[Script Info]\nTitle: Not subtitles")).toThrow(/no \[Events\]/);
  });
});

describe("parseTimecode", () => {
  it("reads a fraction as a decimal one", () => {
    expect(parseTimecode("0:00:01.5")).toBe(150);
    expect(parseTimecode("0:00:01.05")).toBe(105);
    expect(parseTimecode("0:01:00")).toBe(6000);
  });

  it("throws on anything else", () => {
    expect(() => parseTimecode("soon")).toThrow(/isn't a time/);
  });
});

describe("parseColor", () => {
  it("reads hexadecimal and decimal colors, dropping the alpha", () => {
    expect(parseColor("&H8000FFFF")).toBe("#FFFF00");
    expect(parseColor("&HFF0000&")).toBe("#0000FF");
    expect(parseColor("255")).toBe("#FF0000");
  });
});

describe("parseKaraoke", () => {
  it("times each syllable from the end of the one before", () => {
    expect(parseKaraoke("{\\k20}Hel{\\kf30}lo {\\K10}{\\ko40}world").syllables).toEqual([
      { start: 0, duration: 20, text: "Hel", tags: [] },
      { start: 20, duration: 30, text: "lo ", tags: [] },
      { start: 50, duration: 10, text: "", tags: [] },
      { start: 60, duration: 40, text: "world", tags: [] },
    ]);
  });

  it("drops drawings and turns hard breaks into spaces", () => {
    const { syllables } = parseKaraoke(
      "{\\k10\\alpha&H80&}{\\p1}m 0 0 l 5 0{\\p0}{\\k20}one\\Ntwo\\hthree",
    );
    expect(syllables).toEqual([
      { start: 0, duration: 10, text: "", tags: ["\\alpha&H80&"] },
      { start: 10, duration: 20, text: "one two three", tags: [] },
    ]);
  });

  it("says whether the text holds tags other than karaoke ones", () => {
    expect(parseKaraoke("{\\k10}a").formatted).toBe(false);
    expect(parseKaraoke("{\\fad(100,100)}{\\k10}a").formatted).toBe(true);
    expect(parseKaraoke("{a comment}{\\k10}a").formatted).toBe(false);
  });

  it("keeps text before the first karaoke tag as a syllable of no duration", () => {
    expect(parseKaraoke("Oh {\\k50}yeah").syllables).toEqual([
      { start: 0, duration: 0, text: "Oh ", tags: [] },
      { start: 0, duration: 50, text: "yeah", tags: [] },
    ]);
  });

  it("returns untagged text as a single untimed syllable", () => {
    expect(parseKaraoke("{\\i1}Just words")).toEqual({
      timed: false,
      syllables: [{ start: 0, duration: 0, text: "Just words", tags: ["\\i1"] }],
      formatted: true,
    });
  });
});
