// Conversion from an ASS subtitle file to the app's project:
// the lyrics.txt and settings.yaml text, and each voice's timed segments.
// Nothing here touches a store.
//
// The app lays out its own screens, so only the words, their timings, the voices and their styles
// are carried over. A file the app wrote has its title screen, count-ins and instrumental screens
// dropped too, since the settings bring them back.

import yaml from "js-yaml";
import { SUBTITLE_CANVAS, TITLE_SCREEN_DURATION, appName } from "@/constants";
import { AssDocument, AssEvent, AssStyle, parseAss, parseKaraoke } from "./ass";
import { ImportedSyllable, importedTimings, lineMarkup, voiceNames } from "./importedLyrics";
import { fontLeftOut, MARKUP_REMOVED, Warnings } from "./importWarnings";
import { TimedSegment } from "./timedSegments";
import { DEFAULT_VOICE_ID, VoiceId } from "./voices";

// A pause in the singing this long, in centiseconds, starts a new screen.
const SCREEN_BREAK_GAP = 300;
const MAX_SCREEN_LINES = 4;
// What Aegisub calls a new file.
const PLACEHOLDER_TITLE = "Default Aegisub file";
// Aegisub's karaoke templater keeps its code in commented-out lines under these effects.
const TEMPLATE_CODE = /^\s*(template|code|mixin)\b/i;

export const TEMPLATE_LINES_DROPPED =
  "Lines generated by a karaoke effect were dropped, and the lines they were made from imported";
export const FORMATTING_DROPPED =
  "Formatting tags and positions were dropped, since the app lays out its own screens";
export const UNTIMED_LINES = "Lines without karaoke tags were timed from their start and end only";
export const SCREENS_GUESSED =
  "Screen breaks were placed at pauses in the singing, since the file has none";
export const RENDERED_EFFECTS =
  "Most lines are a single positioned word or syllable, as rendered karaoke effects are, so the lyrics are likely unusable";
export const DELAY_UNKNOWN = `The file doesn't say whether its title screen delayed the song, so the timings may be ${TITLE_SCREEN_DURATION} s late`;

export interface AssImport {
  lyrics: string;
  timings: Record<VoiceId, TimedSegment[]>;
  settings: string;
  warnings: string[];
}

interface ImportedLine {
  actor: string;
  style: string;
  syllables: ImportedSyllable[];
  // Centiseconds, in the song's time.
  start: number;
  end: number;
  // On the app's own files, the height of the line on its screen.
  marginV: number;
  breakBefore: boolean;
}

interface Song {
  title?: string;
  artist?: string;
}

/**
 * The app's own files carry its Audio Delay field. Older ones only carry its name.
 */
function isOwnFile(document: AssDocument): boolean {
  return (
    "Audio Delay" in document.info || document.comments.includes(`Script generated by ${appName()}`)
  );
}

function karaokeEffect(event: AssEvent): boolean {
  return event.effect.trim().toLowerCase() === "karaoke";
}

/**
 * The lines to import. A karaoke template keeps each source line under the `karaoke` effect,
 * usually commented out, beside the lines it generated from it.
 * Other effect tools, such as PyonFX, comment the source lines out without marking them.
 * Those are the commented-out lines with karaoke tags, when no shown line has any.
 */
function sourceEvents(document: AssDocument, warnings: Warnings): AssEvent[] {
  const dialogue = document.events.filter((event) => !event.comment);
  const karaoke = document.events.filter(karaokeEffect);
  if (karaoke.length > 0) {
    if (dialogue.some((event) => !karaokeEffect(event))) {
      warnings.add(TEMPLATE_LINES_DROPPED);
    }
    return karaoke;
  }
  const timed = (event: AssEvent) => parseKaraoke(event.text).timed;
  const commented = document.events.filter(
    (event) => event.comment && !TEMPLATE_CODE.test(event.effect) && timed(event),
  );
  if (commented.length > 0 && !dialogue.some(timed)) {
    if (dialogue.length > 0) {
      warnings.add(TEMPLATE_LINES_DROPPED);
    }
    return commented;
  }
  return dialogue;
}

/**
 * Whether most lines draw a single positioned word or less, as an effect tool's output does
 * once its source lines are gone.
 */
function looksRendered(events: AssEvent[]): boolean {
  const rendered = events.filter(
    (event) => /\\(pos|move)\s*\(/.test(event.text) && drawnText(event).split(/\s+/).length <= 1,
  );
  return rendered.length * 2 > events.length;
}

function drawnText(event: AssEvent): string {
  return parseKaraoke(event.text)
    .syllables.map((syllable) => syllable.text)
    .join("")
    .trim();
}

/**
 * The app writes the title screen first, as two lines shown from the start.
 * The title is sung over the first half of the screen and the artist over the second.
 */
function titleScreen(events: AssEvent[]): Song | null {
  const half = Math.round(TITLE_SCREEN_DURATION * 50);
  const sung = (event: AssEvent | undefined, start: number) => {
    const last = event ? parseKaraoke(event.text).syllables.at(-1) : undefined;
    return event?.start === 0 && last?.start === start && last.duration === half;
  };
  const [title, artist] = events;
  if (!sung(title, 0) || !sung(artist, half)) {
    return null;
  }
  return { title: drawnText(title), artist: drawnText(artist) };
}

/**
 * The line's syllables, in seconds, or null when it draws nothing.
 * `delay` is how far the video held the song back, in centiseconds.
 */
function importLine(
  event: AssEvent,
  own: boolean,
  delay: number,
  warnings: Warnings,
): ImportedLine | null {
  const karaoke = parseKaraoke(event.text);
  if (karaoke.formatted && !own) {
    warnings.add(FORMATTING_DROPPED);
  }
  const lineStart = event.start - delay;
  const lineEnd = event.end - delay;
  const withoutMarkup = (text: string) => {
    if (!/[/_]/.test(text)) {
      return text;
    }
    warnings.add(MARKUP_REMOVED);
    return text.replace(/[/_]/g, "");
  };

  if (!karaoke.timed) {
    const words = withoutMarkup(karaoke.syllables[0].text).split(/\s+/).filter(Boolean);
    if (words.length === 0) {
      return null;
    }
    warnings.add(UNTIMED_LINES);
    // The words in between are left untimed, and the render spreads them over the line.
    const syllables: ImportedSyllable[] = words.map((word) => ({ word, wordEnd: true }));
    syllables[0].start = lineStart / 100;
    syllables[syllables.length - 1].end = lineEnd / 100;
    return importedLine(event, syllables, lineStart, lineEnd);
  }

  const syllables: ImportedSyllable[] = [];
  const times: { start: number; end: number }[] = [];
  for (const syllable of karaoke.syllables) {
    // The app tags its count-ins with an alpha, and nothing else it writes.
    const countIn = own && syllable.tags.some((tag) => tag.startsWith("\\alpha"));
    const text = countIn ? "" : withoutMarkup(syllable.text);
    const previous = syllables[syllables.length - 1];
    if (previous && /^\s/.test(text)) {
      previous.wordEnd = true;
    }
    const word = text.trim();
    if (word === "") {
      continue;
    }
    syllables.push({ word, wordEnd: /\s$/.test(text) });
    const start = lineStart + syllable.start;
    times.push({ start, end: start + syllable.duration });
  }
  if (syllables.length === 0) {
    return null;
  }

  syllables.forEach((syllable, i) => {
    const { start, end } = times[i];
    // An end at the next start is left open, as the app writes it.
    const open = i + 1 < times.length && times[i + 1].start <= end;
    syllable.start = start / 100;
    syllable.end = open || end <= start ? undefined : end / 100;
  });
  // A commented-out source line's period is when it is sung, not when it is shown.
  // The app's own periods are mostly automatic ones.
  if (!event.comment && !own) {
    syllables[0].displayStart = lineStart / 100;
    syllables[0].displayEnd = lineEnd / 100;
  }
  return importedLine(event, syllables, times[0].start, times[times.length - 1].end);
}

function importedLine(
  event: AssEvent,
  syllables: ImportedSyllable[],
  start: number,
  end: number,
): ImportedLine {
  return {
    actor: event.name.trim(),
    style: event.style,
    syllables,
    start,
    end,
    marginV: event.marginV,
    breakBefore: false,
  };
}

/**
 * Break the app's own lines where each voice's lines go back up the screen.
 * A screen break in the lyrics breaks every voice, so one is only added where the voice hasn't
 * had one since its last line.
 */
function breakAtOwnScreens(lines: ImportedLine[], voiceOf: (line: ImportedLine) => VoiceId) {
  const previous = new Map<VoiceId, ImportedLine>();
  const newScreen = new Set<ImportedLine>();
  for (const line of lines) {
    const before = previous.get(voiceOf(line));
    if (before && line.marginV <= before.marginV) {
      newScreen.add(line);
    }
    previous.set(voiceOf(line), line);
  }

  const brokenSince = new Map<VoiceId, boolean>();
  const chronological = [...lines].sort((a, b) => a.start - b.start);
  for (const line of chronological) {
    const voice = voiceOf(line);
    if (newScreen.has(line) && !brokenSince.get(voice)) {
      line.breakBefore = true;
      for (const other of brokenSince.keys()) {
        brokenSince.set(other, true);
      }
    }
    brokenSince.set(voice, false);
  }
}

/**
 * Break the lines at pauses in the singing, and split a long run of them into screens of about
 * the same size.
 */
function breakAtPauses(lines: ImportedLine[], warnings: Warnings) {
  const runs: ImportedLine[][] = [];
  let sungUntil = -Infinity;
  for (const line of lines) {
    if (runs.length === 0 || line.start - sungUntil >= SCREEN_BREAK_GAP) {
      runs.push([]);
    }
    runs[runs.length - 1].push(line);
    sungUntil = Math.max(sungUntil, line.end);
  }
  for (const run of runs) {
    const screens = Math.ceil(run.length / MAX_SCREEN_LINES);
    for (let i = 0; i < screens; i++) {
      run[Math.round((i * run.length) / screens)].breakBefore = true;
    }
  }
  lines[0].breakBefore = false;
  if (lines.length > 1) {
    warnings.add(SCREENS_GUESSED);
  }
}

/**
 * The script's height, where libass's defaults fill in a missing one.
 */
function playResY(info: Record<string, string>): number {
  const height = Number(info.PlayResY) || 0;
  const width = Number(info.PlayResX) || 0;
  if (height) return height;
  if (width) return width === 1280 ? 1024 : (width * 3) / 4;
  return 288;
}

function styleSettings(
  document: AssDocument,
  voiceStyles: [VoiceId, AssStyle | undefined][],
  fonts: string[],
  warnings: Warnings,
): Record<string, unknown> {
  const scale = SUBTITLE_CANVAS.height / playResY(document.info);
  const fontName = (style: AssStyle): string | undefined => {
    if (fonts.includes(style.fontName)) {
      return style.fontName;
    }
    warnings.add(fontLeftOut(style.fontName));
    return undefined;
  };
  const fontSize = (style: AssStyle) => Math.round(style.fontSize * scale);
  const outlineWidth = (style: AssStyle) => Math.round(style.outlineWidth * scale * 10) / 10;

  const base = voiceStyles[0]?.[1];
  if (!base) {
    return { videoOptions: {}, voiceStyles: {} };
  }
  const name = fontName(base);
  const videoOptions = {
    font: { ...(name ? { name } : {}), size: fontSize(base), bold: base.bold, italic: base.italic },
    color: {
      primary: base.primary,
      secondary: base.secondary,
      outline: base.outline,
      shadow: base.back,
    },
    outlineWidth: outlineWidth(base),
  };

  const overrides: Record<VoiceId, Record<string, unknown>> = {};
  for (const [voice, style] of voiceStyles) {
    if (!style || style === base) continue;
    const override: Record<string, unknown> = {};
    const name = style.fontName !== base.fontName ? fontName(style) : undefined;
    if (name) override.fontName = name;
    if (fontSize(style) !== fontSize(base)) override.fontSize = fontSize(style);
    if (style.bold !== base.bold) override.bold = style.bold;
    if (style.italic !== base.italic) override.italic = style.italic;
    if (style.primary !== base.primary) override.primary = style.primary;
    if (style.secondary !== base.secondary) override.secondary = style.secondary;
    if (style.outline !== base.outline) override.outline = style.outline;
    if (style.back !== base.back) override.shadow = style.back;
    if (outlineWidth(style) !== outlineWidth(base)) override.outlineWidth = outlineWidth(style);
    if (Object.keys(override).length > 0) overrides[voice] = override;
  }
  return { videoOptions, voiceStyles: overrides };
}

/**
 * Throws when the text isn't an ASS file, or when the converter would produce timings that don't
 * line up with the lyrics it produced.
 */
export function assToProjectFiles(text: string, options: { fonts: string[] }): AssImport {
  const document = parseAss(text);
  const warnings = new Warnings();
  const own = isOwnFile(document);
  const delay = own ? Math.round((Number(document.info["Audio Delay"]) || 0) * 100) : 0;

  let events = sourceEvents(document, warnings);
  if (!own && looksRendered(events)) {
    warnings.add(RENDERED_EFFECTS);
  }
  let song: Song = {};
  const title = own ? titleScreen(events) : null;
  if (title) {
    song = title;
    events = events.slice(2);
    if (!("Audio Delay" in document.info)) {
      warnings.add(DELAY_UNKNOWN);
    }
  } else if (document.info.Title && document.info.Title !== PLACEHOLDER_TITLE) {
    song.title = document.info.Title;
  }

  const fileOrder = events.flatMap((event) => importLine(event, own, delay, warnings) ?? []);
  if (fileOrder.length === 0) {
    throw new Error("The file has no lyrics.");
  }

  // Actors name the singers when the file uses them. Otherwise each style is a voice.
  const actors = new Set(fileOrder.map((line) => line.actor).filter(Boolean));
  const sourceOf = (line: ImportedLine) => (actors.size > 1 && line.actor) || line.style;
  const lines = [...fileOrder].sort((a, b) => a.start - b.start);
  const sources = [...new Set(lines.map(sourceOf))];
  const names = voiceNames(sources, (i) => `Voice ${i + 1}`);
  const multiVoice = sources.length > 1;
  const voiceOf = (line: ImportedLine): VoiceId =>
    multiVoice ? names[sources.indexOf(sourceOf(line))] : DEFAULT_VOICE_ID;

  if (own) {
    breakAtOwnScreens(fileOrder, voiceOf);
  } else {
    breakAtPauses(lines, warnings);
  }

  const pages: string[][] = [];
  const syllablesByVoice: Record<VoiceId, ImportedSyllable[]> = {};
  let previousVoice: VoiceId | null = null;
  for (const line of lines) {
    if (pages.length === 0 || line.breakBefore) {
      pages.push([]);
    }
    const voice = voiceOf(line);
    let markup = lineMarkup(line.syllables, warnings);
    if (multiVoice && voice !== previousVoice) {
      markup = `[${voice}] ${markup}`;
    }
    previousVoice = voice;
    pages[pages.length - 1].push(markup);
    (syllablesByVoice[voice] ??= []).push(...line.syllables);
  }
  const lyrics = pages.map((page) => page.join("\n")).join("\n\n");
  const timings = importedTimings(lyrics, syllablesByVoice, warnings);

  const styles = styleSettings(
    document,
    sources.map((source) => {
      const first = lines.find((line) => sourceOf(line) === source) as ImportedLine;
      return [voiceOf(first), document.styles.find((style) => style.name === first.style)];
    }),
    options.fonts,
    warnings,
  );

  return {
    lyrics,
    timings,
    settings: yaml.dump({ song, ...styles }),
    warnings: warnings.list(),
  };
}
