import { fromEvents, reconcile } from "./timedSegments";
import {
  LyricSegmentIterator,
  LyricsScreen,
  compileLyricTimings,
  setScreenStartTimes,
  adjustScreenTimestamps,
  setSegmentEndTimes,
  createAssFile,
  createMultiVoiceAssFile,
  floatToTimecode,
  LyricsLine,
  KaraokeOptions,
  LyricEvent,
  VerticalAlignment,
  resolveStarts,
  parseLyrics,
} from "./timing";
import { LYRIC_MARKERS, DEFAULT_COUNT_IN_THRESHOLD, DEFAULT_COUNT_IN_DURATION } from "@/constants";
import { LyricSegment } from "./timing";
import { default as BuefyColor } from "buefy/src/utils/color";

// Pinned rather than taken from the default, which is now empty and draws marks instead.
const TEST_COUNT_IN_TEXT = "••• ";

const DEFAULT_OPTIONS: KaraokeOptions = {
  addTitleScreen: true,
  countInMode: "screen",
  countInText: TEST_COUNT_IN_TEXT,
  dynamicCountIns: false,
  countInThreshold: DEFAULT_COUNT_IN_THRESHOLD,
  countInDuration: DEFAULT_COUNT_IN_DURATION,
  addInstrumentalScreens: true,
  addStaggeredLines: true,
  useBackgroundVideo: false,
  outputFormat: "mp4",
  verticalAlignment: VerticalAlignment.Middle,
  font: {
    size: 20,
    name: "Arial Narrow",
  },
  color: {
    background: BuefyColor.parse("#FFFF00"),
    primary: BuefyColor.parse("#FF00FF"),
    secondary: BuefyColor.parse("#00FFFF"),
  },
};

const DEFAULT_FONT_SIZE = 22;

export const testLyrics = "Be bop_a lu bop\nShe's my ba/by\n\nAnd_here's_screen_two";
const testEvents: LyricEvent[] = [
  [1.0, LYRIC_MARKERS.SEGMENT_START],
  [2.0, LYRIC_MARKERS.SEGMENT_END],
  [3.0, LYRIC_MARKERS.SEGMENT_START],
  [4.0, LYRIC_MARKERS.SEGMENT_START],
  [5.0, LYRIC_MARKERS.SEGMENT_START],
  [6.0, LYRIC_MARKERS.SEGMENT_START],
  [7.0, LYRIC_MARKERS.SEGMENT_START],
  [8.0, LYRIC_MARKERS.SEGMENT_START],
  [9.0, LYRIC_MARKERS.SEGMENT_START],
];

export const shortIntroTestEvents = testEvents;

const testAssPreamble = `[Script Info]
; Script generated by The Tüül - https://the-tuul.com
ScriptType: v4.00+
LayoutResX: 512
LayoutResY: 288
PlayResX: 512
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: None
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial Narrow,20,&H00FF00FF,&H00FFFF00,&H0000FFFF,&H00000000,-1,0,0,0,100,100,0,0,1,1,0,8,0,0,0,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:04.00,Default,Singer,0,0,118,,{\\k0}{\\kf200}It's Cøøl to Tüül
Dialogue: 0,0:00:00.00,0:00:04.00,Default,Singer,0,0,148,,{\\k200}{\\kf200}TÜ/ÜL
`;

const testAss =
  testAssPreamble +
  `Dialogue: 0,0:00:04.00,0:00:11.00,Default,Singer,0,0,118,,{\\k0}{\\kf200}${TEST_COUNT_IN_TEXT}{\\kf100}Be bop {\\kf100}{\\kf100}a lu bop

Dialogue: 0,0:00:04.00,0:00:11.00,Default,Singer,0,0,148,,{\\k500}{\\kf100}She's my ba{\\kf100}by


Dialogue: 0,0:00:11.00,0:01:05.00,Default,Singer,0,0,133,,{\\k0}{\\kf100}And {\\kf100}here's {\\kf100}screen {\\kf5100}two
`;

describe("LyricSegmentIterator", () => {
  test("parses segments without markup", () => {
    const iterator = new LyricSegmentIterator(testLyrics);
    const segments = Array.from(iterator);
    expect(segments.length).toBe(8);
    expect(segments[0].text).toBe("Be bop ");
  });

  test("parses segments with markup", () => {
    const iterator = new LyricSegmentIterator(testLyrics, true);
    const segments = Array.from(iterator);
    expect(segments.length).toBe(8);
    expect(segments[0].text).toBe("Be bop_");
  });

  test("handles leading newlines", () => {
    const lyricsWithLeadingNewlines = "\n\nHello world";
    const iterator = new LyricSegmentIterator(lyricsWithLeadingNewlines);
    const segments = Array.from(iterator);
    expect(segments.length).toBe(1);
    expect(segments[0].text).toBe("Hello world");
  });

  test("handles only newlines", () => {
    const justNewlines = "\n\n\n";
    const iterator = new LyricSegmentIterator(justNewlines);
    const segments = Array.from(iterator);
    expect(segments.length).toBe(0);
  });

  test("trims leading spaces", () => {
    const lyrics = "Line 1\n Line 2";
    const iterator = new LyricSegmentIterator(lyrics);
    const segments = Array.from(iterator);
    expect(segments.length).toBe(2);
    expect(segments[1].text).toBe("Line 2");
  });
});

test("compileLyricTimings", () => {
  const screens = compileLyricTimings(fromEvents(testLyrics, testEvents));
  expect(screens.length).toBe(2);
  expect(screens[0].lines.length).toBe(2);
  expect(screens[0].lines[0].segments.length).toBe(2);
  expect(screens[1].lines[0].segments.length).toBe(4);
});

test("setSegmentEndTimes", () => {
  const initialScreens = compileLyricTimings(fromEvents(testLyrics, testEvents));
  const songDuration = 60;
  const screens = setSegmentEndTimes(initialScreens, songDuration);
  expect(screens[0].lines[0].segments[0].endTimestamp).toBe(2.0);
  expect(screens[0].lines[0].segments[1].endTimestamp).toBe(4.0);
  expect(screens[0].lines[1].segments[0].endTimestamp).toBe(5.0);
  expect(screens[0].lines[1].segments[1].endTimestamp).toBe(6.0);
  expect(screens[1].lines[0].segments[0].endTimestamp).toBe(7.0);
});

test("LyricSegment", () => {
  const segment = new LyricSegment("boop", 2.0, 3.0);
  expect(segment.toAss()).toBe("{\\kf100}boop");

  const underSecondSegment = new LyricSegment("baby", 0.5, 0.75);
  expect(underSecondSegment.toAss()).toBe("{\\kf25}baby");
});

// test('LyricScreen does ass', () => {
//     const screen = new LyricsScreen();
//     screen.toAss
// });

test("LyricScreen handles custom Y offset", () => {
  const screen = new LyricsScreen([
    new LyricsLine([new LyricSegment("one", 1.0)]),
    new LyricsLine([new LyricSegment("two", 2.0)]),
  ]);

  // 2 lines: one 33 slot plus the last line's glyph block (22 * 1.12), centred on 144
  expect(screen.getLineY(0, DEFAULT_FONT_SIZE)).toBe(115);

  // Laid out as a 4-line block instead of its own 2, so it starts a line higher
  screen.positionAsLineCount = 4;
  expect(screen.getLineY(0, DEFAULT_FONT_SIZE)).toBe(82);
  expect(screen.getLineY(1, DEFAULT_FONT_SIZE)).toBe(115);
});

test("LyricScreen respects vertical alignment", () => {
  const screen = new LyricsScreen([
    new LyricsLine([new LyricSegment("one", 1.0)]),
    new LyricsLine([new LyricSegment("two", 2.0)]),
  ]);

  expect(screen.getLineY(0, DEFAULT_FONT_SIZE)).toBe(115);
  expect(screen.getLineY(0, DEFAULT_FONT_SIZE, VerticalAlignment.Top)).toBe(33);
  expect(screen.getLineY(0, DEFAULT_FONT_SIZE, VerticalAlignment.Bottom)).toBe(288 - 33 * 3);

  expect(screen.getLineY(1, DEFAULT_FONT_SIZE)).toBe(115 + 33);
  expect(screen.getLineY(1, DEFAULT_FONT_SIZE, VerticalAlignment.Top)).toBe(33 * 2);
  expect(screen.getLineY(1, DEFAULT_FONT_SIZE, VerticalAlignment.Bottom)).toBe(288 - 33 * 2);
});

test("setScreenStartTimes", () => {
  const screens = compileLyricTimings(fromEvents(testLyrics, testEvents));
  const adjusted = setScreenStartTimes(screens);
  expect(adjusted[0].startTimestamp).toBe(0.0);
});

test("adjustTimestamps", () => {
  const screens = setScreenStartTimes(compileLyricTimings(fromEvents(testLyrics, testEvents)));

  const adjusted = adjustScreenTimestamps(screens, 1.0);
  expect(adjusted[0].lines[0].timestamp).toBe(2.0);
  expect(adjusted[0].startTimestamp).toBe(1.0);
});

test("createAssFileForShortIntroSong", () => {
  const songDuration = 60.0;
  const options: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addInstrumentalScreens: false,
    addStaggeredLines: false,
  };
  const assFile = createAssFile(
    fromEvents(testLyrics, shortIntroTestEvents),
    songDuration,
    "It's Cøøl to Tüül",
    "TÜ/ÜL",
    options,
  );
  expect(assFile).toBe(testAss);
});

test("createAssFile handles timings without lyrics", () => {
  // A timings file can be loaded before lyrics are entered. That should yield an event-less ASS file,
  // not a crash in the screen decorators.
  const songDuration = 60.0;
  const timings: LyricEvent[] = [
    [1.0, LYRIC_MARKERS.SEGMENT_START],
    [2.0, LYRIC_MARKERS.SEGMENT_END],
  ];
  const assFile = createAssFile(
    fromEvents("", timings),
    songDuration,
    "It's Cøøl to Tüül",
    "TÜ/ÜL",
    DEFAULT_OPTIONS,
  );
  const headerOnly = testAssPreamble.slice(0, testAssPreamble.indexOf("Dialogue:"));
  expect(assFile).toBe(headerOnly);
});

test("addCountIn", () => {
  const songDuration = 60.0;
  const lyrics = "That was a long intro\nToo bad nothing rhymes with intro";
  const timings: LyricEvent[] = [
    [100.0, LYRIC_MARKERS.SEGMENT_START],
    [105.0, LYRIC_MARKERS.SEGMENT_START],
  ];
  const options: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addInstrumentalScreens: false,
    addStaggeredLines: false,
  };
  let assFile = createAssFile(
    fromEvents(lyrics, timings),
    songDuration,
    "It's Cøøl to Tüül",
    "TÜ/ÜL",
    options,
  );

  const expected =
    testAssPreamble +
    `Dialogue: 0,0:00:04.00,0:01:00.00,Default,Singer,0,0,118,,{\\k9400}{\\kf200}${TEST_COUNT_IN_TEXT}{\\kf500}That was a long intro

Dialogue: 0,0:00:04.00,0:01:00.00,Default,Singer,0,0,148,,{\\k10100}{\\kf-4500}Too bad nothing rhymes with intro
`;
  expect(assFile).toBe(expected);
});

test("addCountInToSevenSecondIntro", () => {
  // An intro between 7-8 seconds has a count-in that makes the intro between 4-5 seconds.
  // So we can't start playing audio until after the title screen.
  // So timings get moved up a little bit/
  const songDuration = 60.0;

  // a corner case when the first event is between 7 and 8 seconds
  const sevenSecondEvents: LyricEvent[] = [
    [7.5, LYRIC_MARKERS.SEGMENT_START],
    [8.5, LYRIC_MARKERS.SEGMENT_END],
    [9.0, LYRIC_MARKERS.SEGMENT_START],
    [10.0, LYRIC_MARKERS.SEGMENT_START],
    [11.0, LYRIC_MARKERS.SEGMENT_START],
    [12.0, LYRIC_MARKERS.SEGMENT_START],
    [13.0, LYRIC_MARKERS.SEGMENT_START],
    [14.0, LYRIC_MARKERS.SEGMENT_START],
    [15.0, LYRIC_MARKERS.SEGMENT_START],
  ];
  const sevenSecondAss =
    testAssPreamble +
    `Dialogue: 0,0:00:04.00,0:00:12.00,Default,Singer,0,0,118,,{\\k150}{\\kf200}${TEST_COUNT_IN_TEXT}{\\kf100}Be bop {\\kf50}{\\kf100}a lu bop

Dialogue: 0,0:00:04.00,0:00:12.00,Default,Singer,0,0,148,,{\\k600}{\\kf100}She's my ba{\\kf100}by


Dialogue: 0,0:00:12.00,0:01:00.00,Default,Singer,0,0,133,,{\\k0}{\\kf100}And {\\kf100}here's {\\kf100}screen {\\kf4500}two
`;
  const options: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addInstrumentalScreens: false,
    addStaggeredLines: false,
  };

  const assFile = createAssFile(
    fromEvents(testLyrics, sevenSecondEvents),
    songDuration,
    "It's Cøøl to Tüül",
    "TÜ/ÜL",
    options,
  );
  expect(assFile).toBe(sevenSecondAss);
});

test("floatToTimecode", () => {
  expect(floatToTimecode(0)).toBe("0:00:00.00");
  expect(floatToTimecode(25.42)).toBe("0:00:25.42");
  expect(floatToTimecode(60)).toBe("0:01:00.00");
});

test("floatToTimecode carries a rounded-up fraction", () => {
  expect(floatToTimecode(44.996)).toBe("0:00:45.00");
  expect(floatToTimecode(59.999)).toBe("0:01:00.00");
  expect(floatToTimecode(119.998)).toBe("0:02:00.00");
  expect(floatToTimecode(3599.999)).toBe("1:00:00.00");
  expect(floatToTimecode(25.994)).toBe("0:00:25.99");
});

test("compileLyricTimings handles more events than segments", () => {
  const shortLyrics = "Hello world"; // 1 segment
  const tooManyEvents: LyricEvent[] = [
    [1.0, LYRIC_MARKERS.SEGMENT_START],
    [2.0, LYRIC_MARKERS.SEGMENT_START],
    [3.0, LYRIC_MARKERS.SEGMENT_START],
    [4.0, LYRIC_MARKERS.SEGMENT_START],
    [5.0, LYRIC_MARKERS.SEGMENT_START],
  ];

  // Surplus events are kept as textless segments rather than discarded, and draw nothing.
  const segments = fromEvents(shortLyrics, tooManyEvents);
  expect(segments.length).toBe(5);

  const screens = compileLyricTimings(segments);
  expect(screens.length).toBe(1);
  expect(screens[0].lines.length).toBe(1);
  expect(screens[0].lines[0].segments.length).toBe(1);
});

test("compileLyricTimings skips an untimed segment but keeps its line break", () => {
  const screens = compileLyricTimings([
    { text: "one_", start: 1.0 },
    { text: "two\n" }, // untimed, and ends the line
    { text: "three", start: 3.0 },
  ]);

  expect(screens.length).toBe(1);
  expect(screens[0].lines.length).toBe(2);
  expect(screens[0].lines[0].segments.map((s) => s.text)).toEqual(["one "]);
  expect(screens[0].lines[1].segments.map((s) => s.text)).toEqual(["three"]);
});

test("compileLyricTimings renders a partially timed project", () => {
  const screens = compileLyricTimings(fromEvents(testLyrics, testEvents.slice(0, 3)));

  // The timed head renders. The untimed tail contributes its breaks but no drawn text.
  expect(screens.length).toBe(1);
  expect(screens[0].lines[0].segments.map((s) => s.text)).toEqual(["Be bop ", "a lu bop\n"]);
});

describe("createMultiVoiceAssFile", () => {
  const noAuxOptions: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addTitleScreen: false,
    countInMode: "none",
    addInstrumentalScreens: false,
    addStaggeredLines: false,
  };

  it("returns empty string when there are no tracks", () => {
    expect(createMultiVoiceAssFile([], 10, "T", "A")).toBe("");
  });

  it("emits one style per voice and events tagged with each voice's style", () => {
    const tracks = [
      {
        voice: "Anna",
        segments: fromEvents("Hello\n", [[1.0, LYRIC_MARKERS.SEGMENT_START]]),
        options: noAuxOptions,
      },
      {
        voice: "Ben",
        segments: fromEvents("World\n", [[2.0, LYRIC_MARKERS.SEGMENT_START]]),
        options: noAuxOptions,
      },
    ];
    const ass = createMultiVoiceAssFile(tracks, 10, "T", "A");

    // One style row per voice
    expect(ass).toContain("Style: V0,");
    expect(ass).toContain("Style: V1,");
    // Dialogue events reference each voice's style (",V0," is unique to events)
    expect(ass).toContain(",V0,");
    expect(ass).toContain(",V1,");
    // Both voices' lyrics are present
    expect(ass).toContain("Hello");
    expect(ass).toContain("World");
    // A single shared document (one [Events] section)
    expect(ass.match(/\[Events\]/g)?.length).toBe(1);
  });
});

describe("multi-voice vertical lanes", () => {
  function marginVsForStyle(ass: string, style: string): number[] {
    return ass
      .split("\n")
      .filter((l) => l.startsWith("Dialogue:") && l.split(",")[3] === style)
      .map((l) => Number(l.split(",")[7]));
  }

  it("centers lines within the lane when verticalZone is set", () => {
    const screen = new LyricsScreen([new LyricsLine([new LyricSegment("a", 1, 2)])]);
    screen.verticalZone = { top: 160, height: 160 };
    // 1 line, fontSize 20, lane middle 240: half a glyph block (20 * 1.12) above it
    expect(screen.getLineY(0, 20)).toBe(229);
  });

  it("keeps the staggered line-count correction inside a lane", () => {
    const screen = new LyricsScreen([new LyricsLine([new LyricSegment("a", 1, 2)])]);
    screen.verticalZone = { top: 0, height: 144 };
    // Lane middle 72. As its own 1-line block, fontSize 20 => half a glyph block above it
    expect(screen.getLineY(0, 20)).toBe(61);
    // Laid out as the 2-line block it displaces => the lane's top slot
    screen.positionAsLineCount = 2;
    expect(screen.getLineY(0, 20)).toBe(46);
  });

  it("puts a staggered line in the lane's top slot, not between the lines it replaces", () => {
    // A short screen displayed early over a 2-line screen must land where that screen's first line was.
    // Lanes are assigned after the staggering pass, so a correction expressed as an absolute Y would
    // be computed for the full frame and then dropped, leaving the early line halfway down the
    // outgoing block and colliding with it.
    const staggered: KaraokeOptions = {
      ...DEFAULT_OPTIONS,
      addTitleScreen: false,
      countInMode: "none",
      addInstrumentalScreens: false,
      addStaggeredLines: true,
      font: { ...DEFAULT_OPTIONS.font, size: 20 },
    };
    const aTimings: LyricEvent[] = [1.0, 2.0, 3.0, 4.0, 5.0].map(
      (t) => [t, LYRIC_MARKERS.SEGMENT_START] as LyricEvent,
    );
    const tracks = [
      {
        voice: "A",
        segments: fromEvents("a one\na two\n\nb one\nb two\n\nc one", aTimings),
        options: staggered,
      },
      {
        voice: "B",
        segments: fromEvents("b line", [[5.5, LYRIC_MARKERS.SEGMENT_START]]),
        options: staggered,
      },
    ];
    const v0 = marginVsForStyle(createMultiVoiceAssFile(tracks, 10, "T", "A"), "V0");
    // lineHeight 30, lane 0 spans 0..144 so its middle is 72: a 2-line block sits at 46 and 76,
    // and the early single line joins it at 46.
    expect(v0).toContain(46);
    // 61 would be a lone line centred in the lane, overlapping the outgoing line at 76.
    expect(v0).not.toContain(61);
  });

  it("puts simultaneous voices in separate vertical lanes (voice 0 above voice 1)", () => {
    const noAux: KaraokeOptions = {
      ...DEFAULT_OPTIONS,
      addTitleScreen: false,
      countInMode: "none",
      addInstrumentalScreens: false,
      addStaggeredLines: false,
    };
    const tracks = [
      {
        voice: "A",
        segments: fromEvents("a one\n", [[1.0, LYRIC_MARKERS.SEGMENT_START]]),
        options: noAux,
      },
      {
        voice: "B",
        segments: fromEvents("b one\n", [[1.0, LYRIC_MARKERS.SEGMENT_START]]),
        options: noAux,
      },
    ];
    const ass = createMultiVoiceAssFile(tracks, 10, "T", "A");
    const v0 = marginVsForStyle(ass, "V0");
    const v1 = marginVsForStyle(ass, "V1");
    // V0's lane sits entirely above V1's lane.
    expect(Math.max(...v0)).toBeLessThan(Math.min(...v1));
  });
});

describe("setSegmentEndTimes overlap clamp", () => {
  it("clamps an explicit end that extends past the next segment's start", () => {
    const s1 = new LyricSegment("a", 1.0, 5.0); // explicit end 5.0...
    const s2 = new LyricSegment("b", 3.0); // ...but next segment starts at 3.0
    const screen = new LyricsScreen([new LyricsLine([s1, s2])]);
    setSegmentEndTimes([screen], 10);
    expect(s1.endTimestamp).toBe(3.0); // clamped to the next start
    expect(s2.endTimestamp).toBe(10); // last segment inferred to song duration
  });

  it("leaves an explicit end that fits before the next segment", () => {
    const s1 = new LyricSegment("a", 1.0, 2.0);
    const s2 = new LyricSegment("b", 3.0);
    const screen = new LyricsScreen([new LyricsLine([s1, s2])]);
    setSegmentEndTimes([screen], 10);
    expect(s1.endTimestamp).toBe(2.0);
  });
});

describe("resolveStarts", () => {
  it("spreads a run of holes between the timings on either side", () => {
    const resolved = resolveStarts([
      { text: "one_", start: 1.0 },
      { text: "al/", start: 2.0 },
      { text: "chem/" },
      { text: "y_" },
      { text: "three", start: 3.0 },
    ]);

    // "al"(2) "chem"(4) "y"(1) share the 1s span by the text each one draws.
    expect(resolved.map((s) => s.start)).toEqual([1.0, 2.0, 2 + 2 / 7, 2 + 6 / 7, 3.0]);
  });

  it("starts a hole at the previous segment's release, not inside it", () => {
    // Pasting a line back between two timed ones. Anchoring on "two"'s start instead put the hole
    // at 2.75, inside "two"'s own span, and the region layer dropped the rectangle as an overlap.
    const resolved = resolveStarts([
      { text: "one_", start: 1.0 },
      { text: "two\n", start: 2.0, end: 2.9 },
      { text: "three_" },
      { text: "four\n" },
      { text: "five_", start: 5.0 },
      { text: "six", start: 6.0 },
    ]);

    expect(resolved[2].start).toBeCloseTo(2.9, 5);
    expect(resolved[3].start).toBeGreaterThan(2.9);
    expect(resolved[3].start).toBeLessThan(5.0);
  });

  it("leaves an untimed tail alone, because that is work not yet done", () => {
    const resolved = resolveStarts([
      { text: "one_", start: 1.0 },
      { text: "two_" },
      { text: "three" },
    ]);

    expect(resolved.map((s) => s.start)).toEqual([1.0, undefined, undefined]);
  });

  it("leaves an untimed head alone", () => {
    const resolved = resolveStarts([
      { text: "one_" },
      { text: "two_" },
      { text: "three", start: 3.0 },
    ]);

    expect(resolved.map((s) => s.start)).toEqual([undefined, undefined, 3.0]);
  });

  it("does not mutate its input", () => {
    const segments = [{ text: "a_", start: 1.0 }, { text: "b_" }, { text: "c", start: 3.0 }];
    resolveStarts(segments);
    expect(segments[1].start).toBeUndefined();
  });
});

test("a word split after timing still renders, with its syllables spread", () => {
  const timed = fromEvents("one_alchemy_three", [
    [1.0, LYRIC_MARKERS.SEGMENT_START],
    [2.0, LYRIC_MARKERS.SEGMENT_START],
    [3.0, LYRIC_MARKERS.SEGMENT_START],
  ]);
  const split = reconcile(timed, parseLyrics("one_al/chem/y_three", true));

  const screens = compileLyricTimings(resolveStarts(split));
  const drawn = screens.flatMap((s) => s.lines.flatMap((l) => l.segments.map((x) => x.text)));

  // Before interpolation the untimed syllables were dropped and the line read "one althree".
  expect(drawn.join("")).toBe("one alchemy three");
});
