import { fromEvents, reconcile } from "./timedSegments";
import {
  LyricSegmentIterator,
  LyricsScreen,
  compileLyricTimings,
  setScreenStartTimes,
  adjustScreenTimestamps,
  setSegmentEndTimes,
  createAssFile,
  createMultiVoiceAssFile,
  floatToTimecode,
  LyricsLine,
  KaraokeOptions,
  LyricEvent,
  VerticalAlignment,
  resolveStarts,
  parseLyrics,
  joinLyrics,
  withFallbackFonts,
  layOutVoices,
} from "./timing";
import { LYRIC_MARKERS, DEFAULT_COUNT_IN_THRESHOLD, DEFAULT_COUNT_IN_DURATION } from "@/constants";
import { LyricSegment } from "./timing";
import { songOffset } from "./screenSlots";
import { default as BuefyColor } from "buefy/src/utils/color";

// Pinned rather than taken from the default, which is now empty and draws marks instead.
const TEST_COUNT_IN_TEXT = "••• ";

const DEFAULT_OPTIONS: KaraokeOptions = {
  addTitleScreen: true,
  countInMode: "screen",
  countInText: TEST_COUNT_IN_TEXT,
  dynamicCountIns: false,
  countInThreshold: DEFAULT_COUNT_IN_THRESHOLD,
  countInDuration: DEFAULT_COUNT_IN_DURATION,
  addInstrumentalScreens: true,
  addStaggeredLines: true,
  useStoredDisplayPeriods: true,
  useBackgroundVideo: false,
  outputFormat: "mp4",
  verticalAlignment: VerticalAlignment.Middle,
  lineSpacing: 1.5,
  topMargin: 1.5,
  outlineWidth: 1,
  shadowX: 0,
  shadowY: 0,
  font: {
    size: 20,
    name: "Arial Narrow",
  },
  color: {
    background: BuefyColor.parse("#FFFF00"),
    primary: BuefyColor.parse("#FF00FF"),
    secondary: BuefyColor.parse("#00FFFF"),
    outline: BuefyColor.parse("#FFFF00"),
    shadow: BuefyColor.parse("black"),
  },
};

const DEFAULT_FONT_SIZE = 22;

export const testLyrics = "Be bop_a lu bop\nShe's my ba/by\n\nAnd_here's_screen_two";
const testEvents: LyricEvent[] = [
  [1.0, LYRIC_MARKERS.SEGMENT_START],
  [2.0, LYRIC_MARKERS.SEGMENT_END],
  [3.0, LYRIC_MARKERS.SEGMENT_START],
  [4.0, LYRIC_MARKERS.SEGMENT_START],
  [5.0, LYRIC_MARKERS.SEGMENT_START],
  [6.0, LYRIC_MARKERS.SEGMENT_START],
  [7.0, LYRIC_MARKERS.SEGMENT_START],
  [8.0, LYRIC_MARKERS.SEGMENT_START],
  [9.0, LYRIC_MARKERS.SEGMENT_START],
];

export const shortIntroTestEvents = testEvents;

const testAssPreamble = `[Script Info]
; Script generated by Le Toul
ScriptType: v4.00+
LayoutResX: 512
LayoutResY: 288
PlayResX: 512
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: None
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial Narrow,20,&H00FF00FF,&H00FFFF00,&H0000FFFF,&H00000000,-1,0,0,0,100,100,0,0,1,1,0,8,0,0,0,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:04.00,Default,Singer,0,0,118,,{\\k0}{\\kf200}It's Cøøl to Tüül
Dialogue: 0,0:00:00.00,0:00:04.00,Default,Singer,0,0,148,,{\\k200}{\\kf200}TÜ/ÜL
`;

const testAss =
  testAssPreamble +
  `Dialogue: 0,0:00:04.00,0:00:11.00,Default,Singer,0,0,118,,{\\fad(0,150)}{\\k0}{\\kf200}${TEST_COUNT_IN_TEXT}{\\kf100}Be bop {\\kf100}{\\kf100}a lu bop

Dialogue: 0,0:00:04.00,0:00:11.00,Default,Singer,0,0,148,,{\\fad(150,0)}{\\k500}{\\kf100}She's my ba{\\kf100}by


Dialogue: 0,0:00:11.00,0:01:05.00,Default,Singer,0,0,133,,{\\k0}{\\kf100}And {\\kf100}here's {\\kf100}screen {\\kf5100}two
`;

describe("LyricSegmentIterator", () => {
  test("parses segments without markup", () => {
    const iterator = new LyricSegmentIterator(testLyrics);
    const segments = Array.from(iterator);
    expect(segments.length).toBe(8);
    expect(segments[0].text).toBe("Be bop ");
  });

  test("parses segments with markup", () => {
    const iterator = new LyricSegmentIterator(testLyrics, true);
    const segments = Array.from(iterator);
    expect(segments.length).toBe(8);
    expect(segments[0].text).toBe("Be bop_");
  });

  test("handles leading newlines", () => {
    const lyricsWithLeadingNewlines = "\n\nHello world";
    const iterator = new LyricSegmentIterator(lyricsWithLeadingNewlines);
    const segments = Array.from(iterator);
    expect(segments.length).toBe(1);
    expect(segments[0].text).toBe("Hello world");
  });

  test("handles only newlines", () => {
    const justNewlines = "\n\n\n";
    const iterator = new LyricSegmentIterator(justNewlines);
    const segments = Array.from(iterator);
    expect(segments.length).toBe(0);
  });

  test("trims leading spaces", () => {
    const lyrics = "Line 1\n Line 2";
    const iterator = new LyricSegmentIterator(lyrics);
    const segments = Array.from(iterator);
    expect(segments.length).toBe(2);
    expect(segments[1].text).toBe("Line 2");
  });
});

describe("parseLyrics", () => {
  const texts = (lyrics: string, includeMarkup = true) =>
    parseLyrics(lyrics, includeMarkup).map(({ text }) => text);

  test("turns a word or syllable break before a line break into the line break", () => {
    expect(texts("foo_\nbar")).toEqual(["foo\n", "bar"]);
    expect(texts("foo/\nbar")).toEqual(["foo\n", "bar"]);
    expect(texts("foo_\n\nbar")).toEqual(["foo\n\n", "bar"]);
    expect(texts("foo\n_bar")).toEqual(["foo\n", "bar"]);
  });

  test("collapses blank lines to one page break", () => {
    expect(texts("foo\n\n\nbar")).toEqual(["foo\n\n", "bar"]);
    expect(texts("foo\n\n\n\nbar")).toEqual(["foo\n\n", "bar"]);
  });

  test("collapses repeated breaks within a line", () => {
    expect(texts("a__b")).toEqual(["a_", "b"]);
    expect(texts("a//b")).toEqual(["a/", "b"]);
    expect(texts("a/_b")).toEqual(["a_", "b"]);
  });

  test("drops a segment of whitespace but keeps its break", () => {
    expect(texts("foo_ \nbar")).toEqual(["foo\n", "bar"]);
    expect(texts("foo\n \nbar")).toEqual(["foo\n\n", "bar"]);
    expect(texts("foo_ _bar")).toEqual(["foo_", "bar"]);
  });

  test("drops the breaks after the last segment", () => {
    expect(texts("foo\n")).toEqual(["foo"]);
    expect(texts("foo_\n")).toEqual(["foo"]);
    expect(texts("foo\n\n\n")).toEqual(["foo"]);
    expect(texts("foo \n ")).toEqual(["foo"]);
  });

  test("reads whitespace at the end of a segment as a word break", () => {
    expect(texts("foo /bar")).toEqual(["foo_", "bar"]);
    expect(texts("foo \nbar")).toEqual(["foo\n", "bar"]);
    expect(texts("foo \n\nbar")).toEqual(["foo\n\n", "bar"]);
    expect(texts("foo bar")).toEqual(["foo bar"]);
    expect(texts("foo /bar", false)).toEqual(["foo ", "bar"]);
  });

  test("counts a spacer on the line below it", () => {
    expect(parseLyrics("/\nfoo\nbar", true)).toEqual([
      { text: "foo\n", spacersBefore: 1 },
      { text: "bar" },
    ]);
    expect(parseLyrics("foo\n/\n/\nbar", true)).toEqual([
      { text: "foo\n" },
      { text: "bar", spacersBefore: 2 },
    ]);
  });

  test("counts a spacer at the bottom of a page on the page's last line", () => {
    expect(parseLyrics("foo\nbar\n/", true)).toEqual([
      { text: "foo\n" },
      { text: "bar", spacersAfter: 1 },
    ]);
    expect(parseLyrics("foo\n/\n\n/\nbar", true)).toEqual([
      { text: "foo\n\n", spacersAfter: 1 },
      { text: "bar", spacersBefore: 1 },
    ]);
  });

  test("counts spacers on a line's first segment", () => {
    expect(parseLyrics("fo/o\n/\nb_ar\n/\n\nbaz", true)).toEqual([
      { text: "fo/" },
      { text: "o\n" },
      { text: "b_", spacersBefore: 1, spacersAfter: 1 },
      { text: "ar\n\n" },
      { text: "baz" },
    ]);
  });

  test("ignores spacers on a page with no line", () => {
    expect(parseLyrics("foo\n\n/\n/\n\nbar", true)).toEqual([{ text: "foo\n\n" }, { text: "bar" }]);
    expect(parseLyrics("/\n\nfoo\n\n/", true)).toEqual([{ text: "foo" }]);
  });

  test("reads a line of slashes and whitespace as one spacer", () => {
    for (const spacer of [" / ", "//", "/ /"]) {
      expect(parseLyrics(`foo\n${spacer}\nbar`, true)).toEqual([
        { text: "foo\n" },
        { text: "bar", spacersBefore: 1 },
      ]);
    }
  });

  test("doesn't read a split at the edge of a line as a spacer", () => {
    expect(parseLyrics("foo/\n/bar", true)).toEqual([{ text: "foo\n" }, { text: "bar" }]);
  });

  test("reads back the lyrics joinLyrics writes", () => {
    for (const lyrics of ["/\nfoo_bar\n/\nba/z\n/\n\n/\n/\nqux\n/", "fo/o\n\nbar", "foo\n/\n/"]) {
      const segments = parseLyrics(lyrics, true);
      expect(joinLyrics(segments)).toBe(lyrics);
      expect(parseLyrics(joinLyrics(segments), true)).toEqual(segments);
    }
  });

  test("counts spacers without markup", () => {
    expect(parseLyrics("foo\n/\nbar", false)).toEqual([
      { text: "foo\n" },
      { text: "bar", spacersBefore: 1 },
    ]);
  });

  test("applies the same rules without markup", () => {
    expect(texts("foo_\nbar", false)).toEqual(["foo\n", "bar"]);
    expect(texts("a__b", false)).toEqual(["a ", "b"]);
    expect(texts("al//chemy", false)).toEqual(["al", "chemy"]);
  });

  test("doesn't draw the markup of a break before a line break", () => {
    const events: LyricEvent[] = [
      [1, LYRIC_MARKERS.SEGMENT_START],
      [2, LYRIC_MARKERS.SEGMENT_START],
    ];
    const [screen] = compileLyricTimings(fromEvents("foo_\nbar", events));
    expect(screen.lines.map((line) => line.segments.map(({ text }) => text.trim()))).toEqual([
      ["foo"],
      ["bar"],
    ]);
  });
});

test("compileLyricTimings", () => {
  const screens = compileLyricTimings(fromEvents(testLyrics, testEvents));
  expect(screens.length).toBe(2);
  expect(screens[0].lines.length).toBe(2);
  expect(screens[0].lines[0].segments.length).toBe(2);
  expect(screens[1].lines[0].segments.length).toBe(4);
});

test("setSegmentEndTimes", () => {
  const initialScreens = compileLyricTimings(fromEvents(testLyrics, testEvents));
  const songDuration = 60;
  const screens = setSegmentEndTimes(initialScreens, songDuration);
  expect(screens[0].lines[0].segments[0].endTimestamp).toBe(2.0);
  expect(screens[0].lines[0].segments[1].endTimestamp).toBe(4.0);
  expect(screens[0].lines[1].segments[0].endTimestamp).toBe(5.0);
  expect(screens[0].lines[1].segments[1].endTimestamp).toBe(6.0);
  expect(screens[1].lines[0].segments[0].endTimestamp).toBe(7.0);
});

test("LyricSegment", () => {
  const segment = new LyricSegment("boop", 2.0, 3.0);
  expect(segment.toAss()).toBe("{\\kf100}boop");

  const underSecondSegment = new LyricSegment("baby", 0.5, 0.75);
  expect(underSecondSegment.toAss()).toBe("{\\kf25}baby");
});

test("karaoke tags don't lose a centisecond to float error", () => {
  // In floats, 27.99 - 25.87 is 2.1199999, and 35.73 - 25.33 is 10.3999999.
  expect(new LyricSegment("▅", 25.87, 27.99).toAss()).toBe("{\\kf212}▅");
  const line = new LyricsLine([new LyricSegment("With", 35.73, 35.97)]);
  expect(line.decorateAssLine(line.segments, 25.33)).toBe("{\\k1040}{\\kf24}With");
});

// test('LyricScreen does ass', () => {
//     const screen = new LyricsScreen();
//     screen.toAss
// });

test("LyricScreen handles custom Y offset", () => {
  const screen = new LyricsScreen([
    new LyricsLine([new LyricSegment("one", 1.0)]),
    new LyricsLine([new LyricSegment("two", 2.0)]),
  ]);

  // 2 lines: one 33 slot plus the last line's glyph block (22 * 1.12), centred on 144
  expect(screen.getLineY(0, DEFAULT_FONT_SIZE)).toBe(115);

  // Laid out as a 4-line block instead of its own 2, so it starts a line higher
  screen.positionAsSlotCount = 4;
  expect(screen.getLineY(0, DEFAULT_FONT_SIZE)).toBe(82);
  expect(screen.getLineY(1, DEFAULT_FONT_SIZE)).toBe(115);
});

test("LyricScreen respects vertical alignment", () => {
  const screen = new LyricsScreen([
    new LyricsLine([new LyricSegment("one", 1.0)]),
    new LyricsLine([new LyricSegment("two", 2.0)]),
  ]);

  expect(screen.getLineY(0, DEFAULT_FONT_SIZE)).toBe(115);
  expect(screen.getLineY(0, DEFAULT_FONT_SIZE, VerticalAlignment.Top)).toBe(33);
  expect(screen.getLineY(0, DEFAULT_FONT_SIZE, VerticalAlignment.Bottom)).toBe(288 - 33 * 3);

  expect(screen.getLineY(1, DEFAULT_FONT_SIZE)).toBe(115 + 33);
  expect(screen.getLineY(1, DEFAULT_FONT_SIZE, VerticalAlignment.Top)).toBe(33 * 2);
  expect(screen.getLineY(1, DEFAULT_FONT_SIZE, VerticalAlignment.Bottom)).toBe(288 - 33 * 2);
});

describe("spacers", () => {
  const slots = (screen: LyricsScreen) => screen.lines.map((_, i) => screen.slotOf(i));

  test("take a slot on their page", () => {
    const screens = compileLyricTimings([
      { text: "a\n", start: 1, spacersBefore: 1 },
      { text: "b\n\n", start: 2, spacersAfter: 1 },
      { text: "c", start: 3 },
    ]);
    expect(screens.map(slots)).toEqual([[1, 2], [0]]);
    expect(screens.map((screen) => screen.slots)).toEqual([4, 1]);
  });

  test("keep their slot next to a line that draws nothing", () => {
    const [screen] = compileLyricTimings([
      { text: "a\n", start: 1 },
      { text: "b\n", spacersBefore: 1 },
      { text: "c", start: 3 },
    ]);
    expect(slots(screen)).toEqual([0, 2]);
    expect(screen.slots).toBe(3);
  });

  test("on a page that draws nothing add no slots to the screen that continues", () => {
    const [screen] = compileLyricTimings([
      { text: "a\n\n", spacersBefore: 2 },
      { text: "b", start: 1 },
    ]);
    expect(slots(screen)).toEqual([0]);
    expect(screen.slots).toBe(1);
  });

  test("move the lines by half a slot in the middle, and by a slot from the edge they're on", () => {
    const [screen] = compileLyricTimings([
      { text: "a\n", start: 1, spacersBefore: 1 },
      { text: "b", start: 2 },
    ]);
    const tops = (alignment: VerticalAlignment) =>
      screen.lines.map((_, i) => screen.getLineY(screen.slotOf(i), DEFAULT_FONT_SIZE, alignment));
    // Without the spacer, the lines sit at 115 and 148.
    expect(tops(VerticalAlignment.Middle)).toEqual([132, 165]);
    expect(tops(VerticalAlignment.Top)).toEqual([66, 99]);
    expect(tops(VerticalAlignment.Bottom)).toEqual([189, 222]);
  });

  test("move the lines in the video", () => {
    const options: KaraokeOptions = {
      ...DEFAULT_OPTIONS,
      addTitleScreen: false,
      countInMode: "none",
      addInstrumentalScreens: false,
      addStaggeredLines: false,
      verticalAlignment: VerticalAlignment.Top,
    };
    const ass = createAssFile(
      [
        { text: "a\n", start: 1, spacersBefore: 1 },
        { text: "b", start: 2 },
      ],
      10,
      "",
      "",
      options,
    );
    const marginVs = ass
      .split("\n")
      .filter((line) => line.startsWith("Dialogue:"))
      .map((line) => Number(line.split(",")[7]));
    expect(marginVs).toEqual([60, 90]);
  });
});

test("LyricScreen follows the line spacing and top margin", () => {
  const screen = new LyricsScreen(
    [1, 2, 3, 4].map((t) => new LyricsLine([new LyricSegment("line", t)])),
  );
  // Gravity.kbp as kbp2video draws it at 1080p: slots at 60, 205, 350 and 495.
  const tops = [0, 1, 2, 3].map((slot) =>
    screen.getLineY(slot, 28, VerticalAlignment.Top, { lineSpacing: 1.381, topMargin: 0.571 }),
  );
  expect(tops).toEqual([60, 205, 350, 495].map((y) => Math.round((y * 288) / 1080)));
});

test("the title screen stays centred whatever the alignment", () => {
  const options: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    countInMode: "none",
    addInstrumentalScreens: false,
    addStaggeredLines: false,
    verticalAlignment: VerticalAlignment.Top,
  };
  const ass = createAssFile([{ text: "a", start: 10 }], 20, "Title", "Artist", options);
  const marginVs = ass
    .split("\n")
    .filter((line) => line.startsWith("Dialogue:"))
    .map((line) => Number(line.split(",")[7]));
  // Two title lines centred on 144, then the lyric line in the top slot.
  expect(marginVs).toEqual([118, 148, 30]);
});

test("setScreenStartTimes", () => {
  const screens = compileLyricTimings(fromEvents(testLyrics, testEvents));
  const adjusted = setScreenStartTimes(screens);
  expect(adjusted[0].startTimestamp).toBe(0.0);
});

test("adjustTimestamps", () => {
  const screens = setScreenStartTimes(compileLyricTimings(fromEvents(testLyrics, testEvents)));

  const adjusted = adjustScreenTimestamps(screens, 1.0);
  expect(adjusted[0].lines[0].timestamp).toBe(2.0);
  expect(adjusted[0].startTimestamp).toBe(1.0);
});

test("createAssFileForShortIntroSong", () => {
  const songDuration = 60.0;
  const options: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addInstrumentalScreens: false,
    addStaggeredLines: false,
  };
  const assFile = createAssFile(
    fromEvents(testLyrics, shortIntroTestEvents),
    songDuration,
    "It's Cøøl to Tüül",
    "TÜ/ÜL",
    options,
  );
  expect(assFile).toBe(testAss);
});

test("createAssFile handles timings without lyrics", () => {
  // A timings file can be loaded before lyrics are entered. That should yield an event-less ASS file,
  // not a crash in the screen decorators.
  const songDuration = 60.0;
  const timings: LyricEvent[] = [
    [1.0, LYRIC_MARKERS.SEGMENT_START],
    [2.0, LYRIC_MARKERS.SEGMENT_END],
  ];
  const assFile = createAssFile(
    fromEvents("", timings),
    songDuration,
    "It's Cøøl to Tüül",
    "TÜ/ÜL",
    DEFAULT_OPTIONS,
  );
  const headerOnly = testAssPreamble.slice(0, testAssPreamble.indexOf("Dialogue:"));
  expect(assFile).toBe(headerOnly);
});

test("addCountIn", () => {
  const songDuration = 60.0;
  const lyrics = "That was a long intro\nToo bad nothing rhymes with intro";
  const timings: LyricEvent[] = [
    [100.0, LYRIC_MARKERS.SEGMENT_START],
    [105.0, LYRIC_MARKERS.SEGMENT_START],
  ];
  const options: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addInstrumentalScreens: false,
    addStaggeredLines: false,
  };
  let assFile = createAssFile(
    fromEvents(lyrics, timings),
    songDuration,
    "It's Cøøl to Tüül",
    "TÜ/ÜL",
    options,
  );

  const expected =
    testAssPreamble +
    `Dialogue: 0,0:00:04.00,0:01:00.00,Default,Singer,0,0,118,,{\\fad(150,0)}{\\k9400}{\\kf200}${TEST_COUNT_IN_TEXT}{\\kf500}That was a long intro

Dialogue: 0,0:00:04.00,0:01:00.00,Default,Singer,0,0,148,,{\\fad(150,0)}{\\k10100}{\\kf-4500}Too bad nothing rhymes with intro
`;
  expect(assFile).toBe(expected);
});

test("addCountInToSevenSecondIntro", () => {
  // An intro between 7-8 seconds has a count-in that makes the intro between 4-5 seconds.
  // So we can't start playing audio until after the title screen.
  // So timings get moved up a little bit/
  const songDuration = 60.0;

  // a corner case when the first event is between 7 and 8 seconds
  const sevenSecondEvents: LyricEvent[] = [
    [7.5, LYRIC_MARKERS.SEGMENT_START],
    [8.5, LYRIC_MARKERS.SEGMENT_END],
    [9.0, LYRIC_MARKERS.SEGMENT_START],
    [10.0, LYRIC_MARKERS.SEGMENT_START],
    [11.0, LYRIC_MARKERS.SEGMENT_START],
    [12.0, LYRIC_MARKERS.SEGMENT_START],
    [13.0, LYRIC_MARKERS.SEGMENT_START],
    [14.0, LYRIC_MARKERS.SEGMENT_START],
    [15.0, LYRIC_MARKERS.SEGMENT_START],
  ];
  const sevenSecondAss =
    testAssPreamble +
    `Dialogue: 0,0:00:04.00,0:00:12.00,Default,Singer,0,0,118,,{\\fad(150,150)}{\\k150}{\\kf200}${TEST_COUNT_IN_TEXT}{\\kf100}Be bop {\\kf50}{\\kf100}a lu bop

Dialogue: 0,0:00:04.00,0:00:12.00,Default,Singer,0,0,148,,{\\fad(150,0)}{\\k600}{\\kf100}She's my ba{\\kf100}by


Dialogue: 0,0:00:12.00,0:01:00.00,Default,Singer,0,0,133,,{\\k0}{\\kf100}And {\\kf100}here's {\\kf100}screen {\\kf4500}two
`;
  const options: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addInstrumentalScreens: false,
    addStaggeredLines: false,
  };

  const assFile = createAssFile(
    fromEvents(testLyrics, sevenSecondEvents),
    songDuration,
    "It's Cøøl to Tüül",
    "TÜ/ÜL",
    options,
  );
  expect(assFile).toBe(sevenSecondAss);
});

test("floatToTimecode", () => {
  expect(floatToTimecode(0)).toBe("0:00:00.00");
  expect(floatToTimecode(25.42)).toBe("0:00:25.42");
  expect(floatToTimecode(60)).toBe("0:01:00.00");
});

test("floatToTimecode carries a rounded-up fraction", () => {
  expect(floatToTimecode(44.996)).toBe("0:00:45.00");
  expect(floatToTimecode(59.999)).toBe("0:01:00.00");
  expect(floatToTimecode(119.998)).toBe("0:02:00.00");
  expect(floatToTimecode(3599.999)).toBe("1:00:00.00");
  expect(floatToTimecode(25.994)).toBe("0:00:25.99");
});

test("compileLyricTimings handles more events than segments", () => {
  const shortLyrics = "Hello world"; // 1 segment
  const tooManyEvents: LyricEvent[] = [
    [1.0, LYRIC_MARKERS.SEGMENT_START],
    [2.0, LYRIC_MARKERS.SEGMENT_START],
    [3.0, LYRIC_MARKERS.SEGMENT_START],
    [4.0, LYRIC_MARKERS.SEGMENT_START],
    [5.0, LYRIC_MARKERS.SEGMENT_START],
  ];

  // Surplus events are kept as textless segments rather than discarded, and draw nothing.
  const segments = fromEvents(shortLyrics, tooManyEvents);
  expect(segments.length).toBe(5);

  const screens = compileLyricTimings(segments);
  expect(screens.length).toBe(1);
  expect(screens[0].lines.length).toBe(1);
  expect(screens[0].lines[0].segments.length).toBe(1);
});

test("compileLyricTimings skips an untimed segment but keeps its line break", () => {
  const screens = compileLyricTimings([
    { text: "one_", start: 1.0 },
    { text: "two\n" }, // untimed, and ends the line
    { text: "three", start: 3.0 },
  ]);

  expect(screens.length).toBe(1);
  expect(screens[0].lines.length).toBe(2);
  expect(screens[0].lines[0].segments.map((s) => s.text)).toEqual(["one "]);
  expect(screens[0].lines[1].segments.map((s) => s.text)).toEqual(["three"]);
});

test("compileLyricTimings renders a partially timed project", () => {
  const screens = compileLyricTimings(fromEvents(testLyrics, testEvents.slice(0, 3)));

  // The timed head renders. The untimed tail contributes its breaks but no drawn text.
  expect(screens.length).toBe(1);
  expect(screens[0].lines[0].segments.map((s) => s.text)).toEqual(["Be bop ", "a lu bop\n"]);
});

describe("withFallbackFonts", () => {
  test("switches a CJK run to the CJK font and back", () => {
    expect(withFallbackFonts("{\\kf100}Sakamoto 坂本 真綾!", "Arial")).toBe(
      "{\\kf100}Sakamoto {\\fnNoto Sans CJK JP}坂本 真綾{\\fn}!",
    );
  });

  test("covers kana, the long vowel mark, CJK punctuation and Hangul", () => {
    expect(withFallbackFonts("「カラオケー」한국", "Arial")).toBe(
      "{\\fnNoto Sans CJK JP}「カラオケー」한국{\\fn}",
    );
  });

  test("switches a run of symbols to the symbol font", () => {
    expect(withFallbackFonts("{\\kf50}➤➤➤➤{\\kf20}May", "Arial")).toBe(
      "{\\kf50}{\\fnDejaVu Sans}➤➤➤➤{\\fn}{\\kf20}May",
    );
  });

  test("keeps the symbols the style's font draws itself", () => {
    const heart = new Set(["♥".codePointAt(0)!]);
    expect(withFallbackFonts("♥♥♥ ➤", "Arial", heart)).toBe("♥♥♥ {\\fnDejaVu Sans}➤{\\fn}");
  });

  test("leaves the text alone in the fallback font it would switch to", () => {
    expect(withFallbackFonts("➤➤ 坂本", "DejaVu Sans")).toBe("➤➤ {\\fnNoto Sans CJK JP}坂本{\\fn}");
  });

  test("switches a whole run when none of its words can be drawn", () => {
    expect(withFallbackFonts("➤➤ ➣➣", "Arial")).toBe("{\\fnDejaVu Sans}➤➤ ➣➣{\\fn}");
  });

  test("leaves Latin text and override blocks alone", () => {
    const line = "{\\fad(100,100)}{\\kf50}Crème brûlée · naïve";
    expect(withFallbackFonts(line, "Arial")).toBe(line);
  });
});

describe("CJK lyrics in the ASS file", () => {
  const options: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addTitleScreen: true,
    countInMode: "none",
    addInstrumentalScreens: false,
    addStaggeredLines: false,
  };
  const segments = fromEvents("残酷な天使\n", [[5.0, LYRIC_MARKERS.SEGMENT_START]]);

  test("names the CJK font when the style's font is a bundled one without CJK glyphs", () => {
    const ass = createAssFile(segments, 10, "Title", "坂本 真綾", options);
    expect(ass).toContain("{\\fnNoto Sans CJK JP}残酷な天使{\\fn}");
    expect(ass).toContain("{\\fnNoto Sans CJK JP}坂本 真綾{\\fn}");
  });

  test("leaves the text alone when the style already uses the CJK font", () => {
    const cjkOptions = { ...options, font: { ...options.font, name: "Noto Sans CJK JP" } };
    expect(createAssFile(segments, 10, "Title", "坂本 真綾", cjkOptions)).not.toContain("\\fn");
  });

  const uploaded = { ...options, font: { ...options.font, name: "My Uploaded Font" } };
  const codePoints = (text: string) => new Set([...text].map((c) => c.codePointAt(0)!));

  test("names the CJK font for an uploaded font without CJK glyphs", () => {
    const ass = createAssFile(segments, 10, "Title", "坂本 真綾", uploaded);
    expect(ass).toContain("{\\fnNoto Sans CJK JP}残酷な天使{\\fn}");
  });

  test("leaves the text alone for an uploaded font that draws all of it", () => {
    const coverage = { "My Uploaded Font": codePoints("残酷な天使坂本真綾") };
    expect(createAssFile(segments, 10, "Title", "坂本 真綾", uploaded, coverage)).not.toContain(
      "\\fn",
    );
  });

  test("names the CJK font for a run the uploaded font only partly draws", () => {
    const coverage = { "My Uploaded Font": codePoints("残酷天使坂本真綾") };
    const ass = createAssFile(segments, 10, "Title", "坂本 真綾", uploaded, coverage);
    expect(ass).toContain("{\\fnNoto Sans CJK JP}残酷な天使{\\fn}");
    expect(ass).not.toContain("{\\fnNoto Sans CJK JP}坂本 真綾{\\fn}");
  });
});

describe("symbols in the ASS file", () => {
  const options: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addTitleScreen: false,
    countInMode: "none",
    addInstrumentalScreens: false,
    addStaggeredLines: false,
    font: { ...DEFAULT_OPTIONS.font, name: "Arial" },
  };
  const segments = fromEvents("♥♥♥_➤➤➤\n", [
    [5.0, LYRIC_MARKERS.SEGMENT_START],
    [6.0, LYRIC_MARKERS.SEGMENT_START],
  ]);

  test("keeps a bundled font's own symbols and switches the rest", () => {
    const ass = createAssFile(segments, 10, "T", "A", options);
    expect(ass).toContain("{\\kf100}♥♥♥ {\\kf400}{\\fnDejaVu Sans}➤➤➤{\\fn}");
  });

  test("switches every symbol for an uploaded font that draws none", () => {
    const uploaded = { ...options, font: { ...options.font, name: "Asmath Free" } };
    const ass = createAssFile(segments, 10, "T", "A", uploaded, { "Asmath Free": new Set() });
    expect(ass).toContain(
      "{\\kf100}{\\fnDejaVu Sans}♥♥♥{\\fn} {\\kf400}{\\fnDejaVu Sans}➤➤➤{\\fn}",
    );
  });
});

describe("createMultiVoiceAssFile", () => {
  const noAuxOptions: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addTitleScreen: false,
    countInMode: "none",
    addInstrumentalScreens: false,
    addStaggeredLines: false,
  };

  it("returns empty string when there are no tracks", () => {
    expect(createMultiVoiceAssFile([], 10, "T", "A")).toBe("");
  });

  it("emits one style per voice and events tagged with each voice's style", () => {
    const tracks = [
      {
        voice: "Anna",
        segments: fromEvents("Hello\n", [[1.0, LYRIC_MARKERS.SEGMENT_START]]),
        options: noAuxOptions,
      },
      {
        voice: "Ben",
        segments: fromEvents("World\n", [[2.0, LYRIC_MARKERS.SEGMENT_START]]),
        options: noAuxOptions,
      },
    ];
    const ass = createMultiVoiceAssFile(tracks, 10, "T", "A");

    // One style row per voice
    expect(ass).toContain("Style: V0,");
    expect(ass).toContain("Style: V1,");
    // Dialogue events reference each voice's style (",V0," is unique to events)
    expect(ass).toContain(",V0,");
    expect(ass).toContain(",V1,");
    // Both voices' lyrics are present
    expect(ass).toContain("Hello");
    expect(ass).toContain("World");
    // A single shared document (one [Events] section)
    expect(ass.match(/\[Events\]/g)?.length).toBe(1);
  });

  it("gives each voice its own outline and shadow", () => {
    const styled: KaraokeOptions = {
      ...noAuxOptions,
      outlineWidth: 2.5,
      shadowX: -2,
      shadowY: 3,
      color: {
        ...noAuxOptions.color,
        outline: BuefyColor.parse("#0000FF"),
        shadow: BuefyColor.parse("#808080"),
      },
    };
    const tracks = [
      {
        voice: "Anna",
        segments: fromEvents("Hello\n", [[1.0, LYRIC_MARKERS.SEGMENT_START]]),
        options: noAuxOptions,
      },
      {
        voice: "Ben",
        segments: fromEvents("World\n", [[2.0, LYRIC_MARKERS.SEGMENT_START]]),
        options: styled,
      },
    ];
    const lines = createMultiVoiceAssFile(tracks, 10, "T", "A").split("\n");
    // OutlineColour, BackColour, Outline and Shadow.
    const outlineAndShadow = (style: string) => {
      const fields = lines.find((line) => line.startsWith(`Style: ${style},`))!.split(",");
      return [fields[5], fields[6], fields[16], fields[17]];
    };
    const text = (style: string) =>
      lines
        .find((line) => line.startsWith("Dialogue:") && line.split(",")[3] === style)!
        .split(",")
        .slice(9)
        .join(",");

    expect(outlineAndShadow("V0")).toEqual(["&H0000FFFF", "&H00000000", "1", "0"]);
    expect(outlineAndShadow("V1")).toEqual(["&H00FF0000", "&H00808080", "2.5", "0"]);
    expect(text("V0")).not.toContain("shad");
    expect(text("V1")).toMatch(/^\{\\xshad-2\\yshad3\}/);
  });
});

describe("multi-voice vertical lanes", () => {
  it("keeps a chain of staggered screens out of the lane except where another voice sings", () => {
    const quick: KaraokeOptions = {
      ...DEFAULT_OPTIONS,
      addTitleScreen: false,
      countInMode: "none",
      addInstrumentalScreens: false,
      addStaggeredLines: true,
    };
    // Four screens of two lines, each following the last closely enough to be staggered.
    const lead = fromEvents(
      "a1\na2\n\nb1\nb2\n\nc1\nc2\n\nd1\nd2",
      [1, 2, 3, 4, 5, 6, 7, 8].map((t) => [t, LYRIC_MARKERS.SEGMENT_START] as LyricEvent),
    );
    const backing = fromEvents("x", [
      [6.2, LYRIC_MARKERS.SEGMENT_START],
      [6.8, LYRIC_MARKERS.SEGMENT_END],
    ]);
    const [render] = layOutVoices(
      [
        { voice: "lead", segments: lead, options: quick },
        { voice: "backing", segments: backing, options: quick },
      ],
      10,
      "",
      "",
    );

    // Only the third screen overlaps the backing voice.
    expect(render.screens.map((screen) => Boolean(screen.verticalZone))).toEqual([
      false,
      false,
      true,
      false,
    ]);
  });

  function marginVsForStyle(ass: string, style: string): number[] {
    return ass
      .split("\n")
      .filter((l) => l.startsWith("Dialogue:") && l.split(",")[3] === style)
      .map((l) => Number(l.split(",")[7]));
  }

  it("centers lines within the lane when verticalZone is set", () => {
    const screen = new LyricsScreen([new LyricsLine([new LyricSegment("a", 1, 2)])]);
    screen.verticalZone = { top: 160, height: 160 };
    // 1 line, fontSize 20, lane middle 240: half a glyph block (20 * 1.12) above it
    expect(screen.getLineY(0, 20)).toBe(229);
  });

  it("keeps the staggered line-count correction inside a lane", () => {
    const screen = new LyricsScreen([new LyricsLine([new LyricSegment("a", 1, 2)])]);
    screen.verticalZone = { top: 0, height: 144 };
    // Lane middle 72. As its own 1-line block, fontSize 20 => half a glyph block above it
    expect(screen.getLineY(0, 20)).toBe(61);
    // Laid out as the 2-line block it displaces => the lane's top slot
    screen.positionAsSlotCount = 2;
    expect(screen.getLineY(0, 20)).toBe(46);
  });

  it("keeps a screen's spacers inside a lane", () => {
    const line = new LyricsLine([new LyricSegment("a", 1, 2)]);
    line.slot = 1;
    const screen = new LyricsScreen([line]);
    screen.slotCount = 2;
    screen.verticalZone = { top: 0, height: 144 };
    // The 2-slot block of the test above, with the line in its bottom slot
    expect(screen.getLineY(screen.slotOf(0), 20)).toBe(46 + 30);
  });

  it("puts a staggered line in the lane's top slot, not between the lines it replaces", () => {
    // A short screen displayed early over a 2-line screen must land where that screen's first line was.
    // Lanes are assigned after the staggering pass, so a correction expressed as an absolute Y would
    // be computed for the full frame and then dropped, leaving the early line halfway down the
    // outgoing block and colliding with it.
    const staggered: KaraokeOptions = {
      ...DEFAULT_OPTIONS,
      addTitleScreen: false,
      countInMode: "none",
      addInstrumentalScreens: false,
      addStaggeredLines: true,
      font: { ...DEFAULT_OPTIONS.font, size: 20 },
    };
    const aTimings: LyricEvent[] = [1.0, 2.0, 3.0, 4.0, 5.0].map(
      (t) => [t, LYRIC_MARKERS.SEGMENT_START] as LyricEvent,
    );
    const tracks = [
      {
        voice: "A",
        segments: fromEvents("a one\na two\n\nb one\nb two\n\nc one", aTimings),
        options: staggered,
      },
      {
        voice: "B",
        segments: fromEvents("b line", [[5.5, LYRIC_MARKERS.SEGMENT_START]]),
        options: staggered,
      },
    ];
    const v0 = marginVsForStyle(createMultiVoiceAssFile(tracks, 10, "T", "A"), "V0");
    // lineHeight 30, lane 0 spans 0..144 so its middle is 72: a 2-line block sits at 46 and 76,
    // and the early single line joins it at 46.
    expect(v0).toContain(46);
    // 61 would be a lone line centred in the lane, overlapping the outgoing line at 76.
    expect(v0).not.toContain(61);
  });

  it("puts simultaneous voices in separate vertical lanes (voice 0 above voice 1)", () => {
    const noAux: KaraokeOptions = {
      ...DEFAULT_OPTIONS,
      addTitleScreen: false,
      countInMode: "none",
      addInstrumentalScreens: false,
      addStaggeredLines: false,
    };
    const tracks = [
      {
        voice: "A",
        segments: fromEvents("a one\n", [[1.0, LYRIC_MARKERS.SEGMENT_START]]),
        options: noAux,
      },
      {
        voice: "B",
        segments: fromEvents("b one\n", [[1.0, LYRIC_MARKERS.SEGMENT_START]]),
        options: noAux,
      },
    ];
    const ass = createMultiVoiceAssFile(tracks, 10, "T", "A");
    const v0 = marginVsForStyle(ass, "V0");
    const v1 = marginVsForStyle(ass, "V1");
    // V0's lane sits entirely above V1's lane.
    expect(Math.max(...v0)).toBeLessThan(Math.min(...v1));
  });
});

describe("multi-voice audio delay", () => {
  const plain: KaraokeOptions = {
    ...DEFAULT_OPTIONS,
    addTitleScreen: false,
    countInMode: "none",
    addInstrumentalScreens: false,
    addStaggeredLines: false,
  };
  const titled: KaraokeOptions = { ...plain, addTitleScreen: true };
  const counted: KaraokeOptions = { ...plain, countInMode: "screen" };
  const voice = (name: string, start: number, options: KaraokeOptions) => ({
    voice: name,
    segments: fromEvents("la\n", [[start, LYRIC_MARKERS.SEGMENT_START]]),
    options,
  });

  // When each voice's first syllable is sung in the video, and how far the video delays the song.
  function firstSung(tracks: ReturnType<typeof voice>[]) {
    return layOutVoices(tracks, 30, "T", "A").map((render) => ({
      at: render.screens
        .flatMap((screen) => (screen.kind === "lyrics" ? screen.segments : []))
        .find((segment) => !segment.countIn)!.timestamp,
      delay: songOffset(render),
    }));
  }

  it("moves every voice past a title screen that delays the song", () => {
    expect(firstSung([voice("A", 1, titled), voice("B", 2, titled)])).toEqual([
      { at: 5, delay: 4 },
      { at: 6, delay: 4 },
    ]);
  });

  it("delays the song for the title screen when another voice starts during it", () => {
    expect(firstSung([voice("A", 10, titled), voice("B", 1, titled)])).toEqual([
      { at: 14, delay: 4 },
      { at: 5, delay: 4 },
    ]);
  });

  it("moves every voice for a quick-start count-in on another voice", () => {
    expect(firstSung([voice("A", 5, counted), voice("B", 0.5, counted)])).toEqual([
      { at: 6.5, delay: 1.5 },
      { at: 2, delay: 1.5 },
    ]);
  });
});

describe("setSegmentEndTimes overlap clamp", () => {
  it("clamps an explicit end that extends past the next segment's start", () => {
    const s1 = new LyricSegment("a", 1.0, 5.0); // explicit end 5.0...
    const s2 = new LyricSegment("b", 3.0); // ...but next segment starts at 3.0
    const screen = new LyricsScreen([new LyricsLine([s1, s2])]);
    setSegmentEndTimes([screen], 10);
    expect(s1.endTimestamp).toBe(3.0); // clamped to the next start
    expect(s2.endTimestamp).toBe(10); // last segment inferred to song duration
  });

  it("leaves an explicit end that fits before the next segment", () => {
    const s1 = new LyricSegment("a", 1.0, 2.0);
    const s2 = new LyricSegment("b", 3.0);
    const screen = new LyricsScreen([new LyricsLine([s1, s2])]);
    setSegmentEndTimes([screen], 10);
    expect(s1.endTimestamp).toBe(2.0);
  });
});

describe("resolveStarts", () => {
  it("spreads a run of holes between the timings on either side", () => {
    const resolved = resolveStarts([
      { text: "one_", start: 1.0 },
      { text: "al/", start: 2.0 },
      { text: "chem/" },
      { text: "y_" },
      { text: "three", start: 3.0 },
    ]);

    // "al"(2) "chem"(4) "y"(1) share the 1s span by the text each one draws.
    expect(resolved.map((s) => s.start)).toEqual([1.0, 2.0, 2 + 2 / 7, 2 + 6 / 7, 3.0]);
  });

  it("starts a hole at the previous segment's release, not inside it", () => {
    // Pasting a line back between two timed ones. Anchoring on "two"'s start instead put the hole
    // at 2.75, inside "two"'s own span, and the region layer dropped the rectangle as an overlap.
    const resolved = resolveStarts([
      { text: "one_", start: 1.0 },
      { text: "two\n", start: 2.0, end: 2.9 },
      { text: "three_" },
      { text: "four\n" },
      { text: "five_", start: 5.0 },
      { text: "six", start: 6.0 },
    ]);

    expect(resolved[2].start).toBeCloseTo(2.9, 5);
    expect(resolved[3].start).toBeGreaterThan(2.9);
    expect(resolved[3].start).toBeLessThan(5.0);
  });

  it("starts a hole with its own end before that end", () => {
    // Replacing a timed "if" with "whe/ther" leaves the end on "ther".
    // Spread up to the next start, "ther" started after its own end.
    const resolved = resolveStarts([
      { text: "whe/", start: 32.31 },
      { text: "ther\n", end: 32.87 },
      { text: "You", start: 33.84 },
    ]);

    expect(resolved[1].start).toBeCloseTo(32.31 + (0.56 * 3) / 7, 5);
  });

  it("spreads the holes after a hole with its own end from that end", () => {
    const resolved = resolveStarts([
      { text: "one_", start: 1.0 },
      { text: "two_", end: 2.0 },
      { text: "three_" },
      { text: "four", start: 4.0 },
    ]);

    expect(resolved[1].start).toBeCloseTo(1.5, 5);
    expect(resolved[2].start).toBeCloseTo(2.0, 5);
  });

  it("drops a hole's own end that comes before the hole can start", () => {
    const resolved = resolveStarts([
      { text: "one_", start: 2.0 },
      { text: "two_", end: 1.5 },
      { text: "three", start: 3.0 },
    ]);

    expect(resolved[1].end).toBeUndefined();
    expect(resolved[1].start).toBeCloseTo(2.5, 5);
  });

  it("drops an end before its own start", () => {
    const resolved = resolveStarts([{ text: "one", start: 2.0, end: 1.5 }]);

    expect(resolved[0].end).toBeUndefined();
  });

  it("leaves an untimed tail alone, because that is work not yet done", () => {
    const resolved = resolveStarts([
      { text: "one_", start: 1.0 },
      { text: "two_" },
      { text: "three" },
    ]);

    expect(resolved.map((s) => s.start)).toEqual([1.0, undefined, undefined]);
  });

  it("leaves an untimed head alone", () => {
    const resolved = resolveStarts([
      { text: "one_" },
      { text: "two_" },
      { text: "three", start: 3.0 },
    ]);

    expect(resolved.map((s) => s.start)).toEqual([undefined, undefined, 3.0]);
  });

  it("does not mutate its input", () => {
    const segments = [{ text: "a_", start: 1.0 }, { text: "b_" }, { text: "c", start: 3.0 }];
    resolveStarts(segments);
    expect(segments[1].start).toBeUndefined();
  });
});

test("a word split after timing still renders, with its syllables spread", () => {
  const timed = fromEvents("one_alchemy_three", [
    [1.0, LYRIC_MARKERS.SEGMENT_START],
    [2.0, LYRIC_MARKERS.SEGMENT_START],
    [3.0, LYRIC_MARKERS.SEGMENT_START],
  ]);
  const split = reconcile(timed, parseLyrics("one_al/chem/y_three", true));

  const screens = compileLyricTimings(resolveStarts(split));
  const drawn = screens.flatMap((s) => s.lines.flatMap((l) => l.segments.map((x) => x.text)));

  // Before interpolation the untimed syllables were dropped and the line read "one althree".
  expect(drawn.join("")).toBe("one alchemy three");
});
